companies:
  type: pandas.CSVDataset
  filepath: ${_base_folder}/01_raw/companies.csv

reviews:
  type: pandas.CSVDataset
  filepath: ${_base_folder}/01_raw/reviews.csv

shuttles:
  type: pandas.ExcelDataset
  filepath: ${_base_folder}/01_raw/shuttles.xlsx

preprocessed_companies:
  type: pandas.ParquetDataset
  filepath: ${_base_folder}/02_intermediate/preprocessed_companies.pq

preprocessed_shuttles:
  type: pandas.ParquetDataset
  filepath: ${_base_folder}/02_intermediate/preprocessed_shuttles.pq

model_input_table:
  type: pandas.ParquetDataset
  filepath: ${_base_folder}/03_primary/model_input_table.pq

_base_folder: data